Create dart.yml for CI
C19-BayShield/bayshield pull request #16
Opened 2020-04-11 22:42 UTC by cameronaaron

2020-04-12 06:10 UTC, tinataleb commented
Thanks for starting this, it'll help us move forward faster with an ease of mind!

2020-04-12 20:44 UTC, Kthulu120 requested changes
Overall good start, now just need to modify and test these workflows on your branch.

2020-04-12 20:44 UTC, Kthulu120 commented on .github/workflows/stale.yml
> +    # The message to post on the issue when tagging it. If none provided, will not mark iusses stale.
Seems like your required to have token for repo and perhaps changing this to would fix it proceeded by adding a github secret to repo.
```
repo-token:  {{ secrets.GITHUB_TOKEN }}
```

2020-04-12 20:44 UTC, Kthulu120 commented on .github/workflows/dart.yml
> +      image:  google/dart:latest
for some reason flutter sdk isn't installed on this container or if it is its not in the PATH so you'll need to add the flutter sdk. [This](https://gist.github.com/Kthulu120/59639e3a81dc8e61f37c78177d39ac20) is the Dart Action that I use to automatically produce builds for flutter on master branch. You'll need to change it to all branches besides that as long as the tests pass this config will work. Just a option.

2020-04-12 20:44 UTC, Kthulu120 commented on .github/workflows/fluttertests.yml
> +uses: axel-op/dart-package-analyzer@v2.0.0
This has to be wrapped by an `on:`  attribute from what the github workflow is telling me.

2020-04-16 05:05 UTC, Kthulu120 commented
Checking in hows progress?

2020-04-19 00:10 UTC, cameronaaron commented
@Kthulu120 Thank you this passes and can be merged

2020-04-19 00:10 UTC, merged